[>DESCRIPTION]
.PP
.B includeres
includes resources (fonts, procsets, patterns, files, etc.) in place of
.B %%IncludeResource
comments in a PostScript document.
The resources are searched for under the resource name, and with an
appropriate extension.
The pipeline
.sp
.RS
extractres file.ps | includeres >out.ps
.RE
.sp
will move all resources appearing in a document to the document prologue,
removing redundant copies.
The output file can then be put through page re-arrangement filters such as
.B psnup
or
.B pstops
safely.

[>AUTHOR]
.SH BUGS
.B includeres
does not alter the
.B %%DocumentNeededResources
comments.
