.TH PSJOIN "1" "November 2003" "psjoin" "User Commands"
.SH NAME
psjoin \- psjoin
.SH SYNOPSIS
.B psjoin
.RI [ option ...]
.IR filename ...
.SH DESCRIPTION
.B psjoin
\- concatenate PostScript files
by Tom Sato <VEF00200@nifty.ne.jp>, http://member.nifty.ne.jp/tsato/
.SS "Option:"
.HP
\fB\-e\fR: force page of each document to an odd page
.HP
\fB\-s\fR: try to close unclosed save operators
.HP
\fB\-p\fR: do not omit the prolog/trailer of the input files
