#!/usr/bin/env perl
# psmerge: use Ghostscript to merge PostScript files produced by same application and setup
#
# Copyright (C) Angus J. C. Duggan 1991-1995
# See file LICENSE for details.

use strict;
use warnings;
my $prog = ($0 =~ m,([^/\\]*)$,) ? $1 : $0;
my $outfile = undef;

usage() unless @ARGV;

while ($ARGV[0] =~ /^-/) {
   $_ = shift;
   if (/^-o(.+)/) {
      $outfile = $1;
   } else {
      usage();
   }
}

$outfile = '-' unless defined $outfile;
exec +(qw(gs -q -dNOPAUSE -dBATCH -sDEVICE=pswrite),
       "-sOutputFile=$outfile", '-f', @ARGV);
die "$prog: Couldn't find Ghostscript (is it installed?), or it failed\n";

sub usage
{
   print STDERR "Usage: $prog [-oout] file...\n";
   exit 1;
}
