.TH PSNUP 1 "PSUtils"
.SH NAME
psnup \- multiple pages per sheet
.SH SYNOPSIS
.B psnup
.RB [ \-p\fIpaper\-size\fR ]
.RB [ \-P\fIpaper\-size\fR ]
.RB [ \-l | \-r | \-f ]
.RB [ \-c ]
.RB [ \-m\fImargin\fR ]
.RB [ \-b\fIborder\fR ]
.RB [ \-d [ \fIlwidth\fR ]]
.RB [ \-\fInup\fR ]
.RB [ \-q ]
.RI [ infile
.RI [ outfile ]]
.SH DESCRIPTION
.B Psnup
imposes multiple logical pages on to each physical sheet of paper.
The input PostScript file should follow the Adobe Document Structuring
Conventions.
.PP
Paper sizes can be given either as a name (see
.BR paper(1))
or as \fBwidth\fRx\fBheight\fR (see
.BR psutils (1)
for the available units).
.PP
The 
.B \-p
option can be used to set the output paper size; otherwise it defaults to
the input paper size; if that is not given, a default value is used (see
.BR paper (1)).
.PP
The
.B \-P
option can be used to set the input paper size; otherwise it defaults to the
output paper size.
.PP
The
.B \-l
option should be used for pages which are in landscape orientation (rotated 90
degrees anticlockwise).
The
.B \-r
option should be used for pages which are in seascape orientation (rotated 90
degrees clockwise), and the
.B \-f
option should be used for pages which have the width and height interchanged,
but are not rotated.
.PP
.B Psnup
normally uses \[oq]row-major\[cq] layout, where adjacent pages are placed in rows
across the paper.
The
.B \-c
option changes the order to \[oq]column-major\[cq], where successive pages are placed
in columns down the paper.
.PP
A margin to leave around the whole page can be specified with the
.B \-m
option.
This is useful for sheets of \[oq]thumbnail\[cq] pages, because the normal
page margins are reduced by putting multiple pages on a single sheet.
.PP
The
.B \-b
option is used to specify a border around each page on a sheet.
.PP
The
.B \-d
option draws a line around the border of each page, of the specified width.
If the \fIlwidth\fR parameter is omitted, a default line width of 1 point is
assumed.
The line width is relative to the original page dimensions,
i.e., it is scaled down with the rest of the page.
.PP
The
.BI \- nup
option selects the number of logical pages to put on each sheet of paper.
This can be any positive integer;
.B psnup
tries to optimise the layout so that the minimum amount of space is wasted.
If
.B psnup
cannot find a layout within its tolerance limit, it will abort with an error
message.
The alternative form
.BI \-n nup
can also be used, for compatibility with other n-up programs.
.PP
.B Psnup
normally prints the page numbers of the pages re-arranged; the
.B \-q
option suppresses this.
.SH EXAMPLES
The potential use of this utility is varied but one particular 
use is in conjunction with 
.BR psbook (1).
For example, using groff to create a PostScript document and lpr as 
the 
.SM UNIX 
print spooler a typical command line might look like this: 
.sp
groff -Tps -ms \fIfile\fP | psbook | psnup -2 | lpr
.sp
where file is a 4 page document this command will result in a 
two page document printing two pages of \fIfile\fP per page and
rearranges the page order to match the input pages 4 and 1 
on the first output page and
pages 2 then 3 of the input document 
on the second output page.
.SH AUTHOR
Written by Angus J. C. Duggan.
.SH "SEE ALSO"
.BR psutils (1),
.BR paper (1)
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
.SH BUGS
.B Psnup
does not accept all DSC comments.
