#!/usr/bin/env python
# Make a test PostScript or PDF file of a given number of pages
# Requires a2ps and ps2pdf
# Simply writes a large page number on each page
# (c) Reuben Thomas 2016-2023
# This file is in the public domain

import os
import sys
import subprocess
from pathlib import Path

# Configuration
lines_per_page = 4
border = 1

# Command-line arguments
paper = sys.argv[1]
pages = int(sys.argv[2])
file = Path(sys.argv[3])
if len(sys.argv) > 4:
    border = sys.argv[4]

# Parse filename
suffix = file.suffix
title = file.stem

# Produce PostScript
text = ('\n' * lines_per_page).join([str(i + 1) for i in range(pages)])
subprocess.run(
    [
        'a2ps',
        f'--medium={paper}',
        f'--title={title}',
        f'--lines-per-page={lines_per_page}',
        f'--portrait',
        f'--columns=1',
        f'--rows=1',
        f'--border={border}',
        f'--no-header',
        f'--output={title}.ps'
    ],
    text=True,
    input=text,
)

# Convert to PDF if required
if suffix == '.pdf':
    subprocess.run(['ps2pdf', f'-sPAPERSIZE={paper}', f'{title}.ps', f'{title}.pdf'])
    os.remove(f'{title}.ps')
