#!/bin/sh
set -e

# FIXME: Common up with psselect-test

# Test with 20 pages
$srcdir/mktestfile 20 > psbook-test.ps
$top_srcdir/psbook ./psbook-test.ps > psbook-20-test.ps
diff -u --ignore-matching-lines=CreationDate $srcdir/psbook-20-expected.ps psbook-20-test.ps

# Test with 3 pages
$srcdir/mktestfile 3 > psbook-test.ps
$top_srcdir/psbook ./psbook-test.ps > psbook-3-test.ps
diff -u --ignore-matching-lines=CreationDate $srcdir/psbook-3-expected.ps psbook-3-test.ps
