#!/bin/sh
set -e

# Test file with 20 pages
$srcdir/mktestfile 20 > psselect-test.ps

# Test --odd
$top_srcdir/psselect --odd ./psselect-test.ps > psselect-odd-test.ps
diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-odd-expected.ps psselect-odd-test.ps

# # Test --even
# $top_srcdir/psselect --even ./psselect-test.ps > psselect-even-test.ps
# diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-even-expected.ps psselect-even-test.ps

# # Test --reverse
# $top_srcdir/psselect --reverse ./psselect-test.ps > psselect-reverse-test.ps
# diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-reverse-expected.ps psselect-reverse-test.ps

# # Test --even and --reverse
# $top_srcdir/psselect --even --reverse ./psselect-test.ps > psselect-even-and-reverse-test.ps
# diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-even-and-reverse-expected.ps psselect-even-and-reverse-test.ps

# # Test positive range
# $top_srcdir/psselect 1-5 ./psselect-test.ps > psselect-positive-range-test.ps
# diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-positive-range-expected.ps psselect-positive-range-test.ps

# # Test negative range
# $top_srcdir/psselect _5-_1 ./psselect-test.ps > psselect-negative-range-test.ps
# diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-negative-range-expected.ps psselect-negative-range-test.ps

# # Test positive-negative range
# $top_srcdir/psselect 2-_2 ./psselect-test.ps > psselect-positive-negative-range-test.ps
# diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-positive-negative-range-expected.ps psselect-positive-negative-range-test.ps

# # Test individual pages and ranges with -p
# $top_srcdir/psselect -p1,3,5,2,4,6,8-10,19 ./psselect-test.ps > psselect-individual-pages-and-ranges-test.ps
# diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-20-expected.ps psselect-individual-pages-and-ranges-test.ps

# # Test options and complex page selection
# $top_srcdir/psselect -o 4-16,_3_-1 ./psselect-test.ps > psselect-options-and-complex-range-test.ps
# diff -u --ignore-matching-lines=CreationDate $srcdir/psselect-options-and-complex-range-expected.ps psselect-options-and-complex-range-test.ps

# # FIXME: Test illegal page range (no -p) with options
