#!/bin/bash
# Run a psutils test

set -e

test_file=$1
name=${1%.sh}
basename=$(basename $name)

# First argument is number of pages for test document
# Remaining arguments are command to run
function test() {
    local pages=$1
    shift
    "$srcdir/mktestfile" "$pages" > "tests/$basename-input.ps"
    tests/psutils-wrapper "$@" "tests/$basename-input.ps" > "tests/$basename-output.ps"
    diff -u --ignore-matching-lines="^%%CreationDate" "$srcdir/$basename-expected.ps" "tests/$basename-output.ps"
}

source $test_file
