#!/bin/bash
# Run a psutils test

set -e

test_file=$1
name=${1%.sh}
basename=$(basename $name)

# Arguments are command to run
function raw_test() {
    eval "$@" "$srcdir/$basename-input.ps" > "tests/$basename-output.ps"
    diff -u --ignore-matching-lines="^\(% \)\?%%CreationDate" "$srcdir/$basename-expected.ps" "tests/$basename-output.ps"
}

# First argument is number of pages for test document
# Remaining arguments are command to run
function test() {
    local paper=$1
    local pages=$2
    shift 2
    # Uncomment to regenerate test files
    #"$srcdir/mktestfile" "$paper" "$pages" > "tests/$basename-input.ps"
    raw_test "$@"
}

source $test_file
